version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiffintrack_backend
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DB_HOST: tiffintrack_postgres
      DB_PORT: 5432
      GDAL_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/libgdal.so
      GEOS_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/libgeos_c.so
    ports:
      - "8003:8003"
    depends_on:
      - postgres
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8003"

  postgres:
    image: postgis/postgis:15-3.4
    container_name: tiffintrack_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-tiffintrack}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - tiffintrack_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  tiffintrack_postgres_data: